### ISSUE TITLE
Wordpress Plugin doesn't show geocoder on Page edit

### ISSUE THREAD

**Issue by hawkeyeP** [halfempty/address-geocoder#18]
I'm not sure if I need to do something special, but the Geocoder form and the saved data fields do not display in the Wordpress plugin App on Android when I go to edit a post.  They display fine when I use a web browser to access the page.  Any ideas?

Thanks for a great plugin!

**Comment by halfempty** [comment]
I'm sorry I don't have any experience with the Android App. Do other plugins' metaboxes show?
