### ISSUE TITLE
Accessing Lat and Lng from functions.php

### ISSUE THREAD

**Issue by addzycullen** [halfempty/address-geocoder#19]
wondered if you might be able to help, Im trying to access the lat and lng of each post to insert into a new table in the database whoch is going to be base of another function.

I have the post ID inserting into this table, however getting the lat and lng seems to be impossible, I've tried so many ways, If you could help, I would really appreciate it.

Here's my function, if you can help i'd really appreciate it.

    function save_lat_lng( $post_id )   
    {  
        global $wpdb;  
        $fields = $_POST['acf']; 
    
    global $post;
    $custom_lat = $_POST[get_geocode_lat( $post->ID )]; 
    $custom_lng = $_POST[get_geocode_lng( $post->ID )];
    // Check that we are editing the right post type  
    if ( 'festival-event' != $_POST['post_type'] ) 
    {  
        return;  
    }  
      
    // Check if we have a lat/lng stored for this property already  
    $check_link = $wpdb->get_row("SELECT * FROM lat_lng_post WHERE post_id = '" . $post_id . "'");  
    if ($check_link != null)   
    {  
        // We already have a lat lng for this post. Update row  
        $wpdb->update(   
        'lat_lng_post',   
        array(   
            "lat" => $custom_lat,
            "lng" => $custom_lng 
        ),   
        array( 'post_id' => $post_id ),   
        array(   
            '%f',  
            '%f'  
        )  
        );  
    }  
    else  
    {  
        // We do not already have a lat lng for this post. Insert row  
        $wpdb->insert(   
        'lat_lng_post',   
        array(   
            'post_id' => $post_id,  
            "lat" => $custom_lat,
            "lng" => $custom_lng
        ),   
        array(   
            '%d',   
            '%f',  
            '%f'  
        )   
        );  
    }  
    }  
    add_action( 'save_post', 'save_lat_lng' )```

**Comment by mgibbs189** [comment]
Sorry, this isn't a support forum :\
